module.exports = {
    FB_PAGE_TOKEN: 'EAACMIRN3ZBR4BAF4IIttwAZCyzFDUR817JrSFFC2yhgZBl6xwrV5CZAcrDqf5JqDDZAL7hAxhlUOgrJU9nNATJzV0o1gGHz46Lh3BXw1u245XSPX4aJPTzzhtWOFDL0l5hJZCRzpQHg19fEVqcT1qHBm0TymCgHVc72bkWyfWXPgZDZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};
